geofence:
  latitude: 51.0486
  longitude: -114.0708
  radius_m: 200

garage:
  entity_id: cover.garage_door
  delay_sec: 5

tesla_account:
  email: "your-email@example.com"
  refresh_token: "your-refresh-token"